# Beforehand, you should set an environment named "dev" with the following secrets:
#   REGISTRY_USERNAME
#   MONGO_ATLAS_URI
#   REGISTRY_PASSWORD

name: Build and Deploy full stack app to Azure Web App
on:
  push:
    branches: [ github ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['20.x']
        mongodb-version: ['7.0']
    environment: dev
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js version ${{ matrix.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'npm'

    - name: Use MongoDB in GitHub Actions # setting up test MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: npm install and test
      env:
        MONGO_ATLAS_URI: 'mongodb://localhost/nasa-mc-db' # test MongoDB
      run: |
        npm install
        npm run test

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.REGISTRY_USERNAME }}
    #     password: ${{ secrets.REGISTRY_PASSWORD }}
  
    # - name: Build the Docker image
    #   run: |
    #     docker build . -t famaten/my-nasa-mc-project
    #     docker push famaten/my-nasa-mc-project

  # deploy:
  #   runs-on: ubuntu-latest
  #   environment: dev
  #   needs: build
  #   steps:
  #   - name: 'Deploy to Azure WebApp'
  #     id: deploy-to-webapp
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
  #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #       images: famaten/my-nasa-mc-project


